[package]
authors = ["Tony B. <tonyb983@gmail.com>"]
default-run = "runner"
edition = "2021"
name = "chessers"
repository = "github.com/tonyb983/chessers"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
